# Generated by Django 5.2.9 on 2025-12-04 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identifier / registration number of the clinic, if available.', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pet_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, help_text='The scanned/screenshot document of the invoice. Uses local filesystem storage in development, S3 in production (configure via DEFAULT_FILE_STORAGE setting).', null=True, upload_to='invoices/')),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from the invoice document using OCR.')),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('subtotal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='claims.claim')),
                ('clinic', models.ForeignKey(blank=True, help_text='The clinic that issued this invoice. May be null if clinic info is not yet extracted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='claims.clinic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Number of units for this line (e.g. 2 boxes of medication).', max_digits=8)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for this line as shown (or implied) on the invoice.', max_digits=10, null=True)),
                ('category', models.CharField(blank=True, help_text='Internal category (e.g. consultation, imaging, surgery, medication).', max_length=128)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate applied to this line, if known (e.g. 21.00 for 21%).', max_digits=5, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='claims.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
